### PR TITLE
the folder name was changed

### PR DESCRIPTION
**Pull request by akbarjonjorayev**

### CODE REVIEW

**Comment by nazarovctrl** [comment]
Folfer name change bolmagan!

**Review by nazarovctrl — CHANGES_REQUESTED** [review]
Folder name ozgartirilmagan

**Comment by akbarjonjorayev** [comment]
Yee kecha scteen tashadimu

**Comment by akbarjonjorayev** [comment]
Ozgartirdim

**Comment by nazarovctrl** [comment]
> Ozgartirdim

Push qildinmi?

**Comment by akbarjonjorayev** [comment]
Yoq endi

**Comment by akbarjonjorayev** [comment]
bopladm 🤦‍♂️

**Pull request merged**
